### ISSUE TITLE
"Functional CSS Tabs Re-Revisited" uses JS...

### ISSUE THREAD

**Issue by Indigo744** [maliMirkec/css-tabs-list#1]
The example at https://css-tricks.com/functional-css-tabs-re-revisited is using some JS (jQuery, even) code, therefore missing the point of pure CSS tabs...

**Comment by maliMirkec** [comment]
Yes, the reason is accessibility, we can't create fully accessible CSS tabs without JavaScript.
I published an article about building pure CSS tabs, and there was a great discussion on HackerNews: https://news.ycombinator.com/item?id=12676660.
The next step was to build pure CSS tabs that accessible, you could read more about it here: https://www.silvestarbistrovic.from.hr/articles/css-tabs-part-ii-accessibility/

**Comment by Indigo744** [comment]
Ah, ok. Maybe add a little paragraph about it at the end of the readme? ;-)

Thanks for your work.
